spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/setyuth
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
  application:
    name: keycloak

server:
  port: 8081

jwt:
  auth:
    converter:
      resource-id: springboot-keycloak-rest-api
      principle-attribute: preferred_username
